language: node_js

node_js:
  - "12"

services:
  - docker
before_isntall:
  - docker build --tag node-docker .

script:
  - docker run node-docker

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-east-2"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-east-2-043536338768"
  on:
    branch: main

after_deploy:
  - echo "done deploying"